### ISSUE TITLE
Unable to inject sidecar containers in helm charts

### ISSUE THREAD

**Issue by yousafsyed-bg** [aws/karpenter#3220]
### Version

__Karpenter Version:__ v0.20.0

__Kubernetes Version:__ v1.2.4
__Helm Chart Version:__ v0.20.0

I am trying to inject a sidecar container using the helm charts https://github.com/aws/karpenter/tree/main/charts/karpenter there is an option to inject the sidecar containers i.e `controller.sidecarContainer` 

My Relevant values.yaml file is 

```yaml
....
controller:
....
  sidecarContainer:
    image: docker.io/lacework/datacollector:6.2.0-sidecar
    imagePullPolicy: Always
    name: lw-agent-sidecar
    env:
      - name: LaceworkLogStdout
        value: "yes"
      - name: LaceworkAccessToken
        valueFrom:
          secretKeyRef:
            name: lacework-agent-access-token
            key: agent-access-token
      - name: LW_KUBERNETES_NODENAME
        valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      - name: LW_EXECUTION_ENV
        value: "EKS_FARGATE"
...
```

but I get following error when upgrading helm chart

```bash
Error: UPGRADE FAILED: template: karpenter/templates/deployment.yaml:117:26: executing "karpenter/templates/deployment.yaml" at <.Values.controller.extraVolumeMounts>: nil pointer evaluating interface {}.controller
```

### Expected Behavior

Should be able to add sidecar containers by using the provided helm chart option  i.e `controller.sidecarContainer` 

### Actual Behavior

When the  sidecar  container configs are injected helm chart uprade or install command crashes with following error

```bash
Error: UPGRADE FAILED: template: karpenter/templates/deployment.yaml:117:26: executing "karpenter/templates/deployment.yaml" at <.Values.controller.extraVolumeMounts>: nil pointer evaluating interface {}.controller
```

### Steps to Reproduce the Problem

1. Create new values.yaml file locally
2. add following code snippet
    ```bash
      extraVolumes:
          - name: lacework-volume
            emptyDir: {}
          - name: cfgmap
            configMap:
              name: lacework-config
              items:
              - key: config.json
                path: config.json
          - name: podinfo
            downwardAPI:
              items:
              - path: "labels"
                fieldRef:
                    fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                    fieldPath: metadata.annotations
      controller:
          # -- Controller image.
          image: "public.ecr.aws/karpenter/controller:v0.22.1@sha256:8aa720d4fc95d4187e1030f4a11996a27181dada9e6054a77b8ae7b4313d3e6b"
          # -- SecurityContext for the controller container.
          securityContext: {}
          # -- Additional environment variables for the controller pod.
          env: []
          # - name: AWS_REGION
          #   value: eu-west-1
        
          # -- Resources for the controller pod.
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          # -- Controller outputPaths - default to stdout only
          outputPaths:
            - stdout
          # -- Controller errorOutputPaths - default to stderr only
          errorOutputPaths:
            - stderr
          # -- Controller log level, defaults to the global log level
          logLevel: ""
          # -- Controller log encoding, defaults to the global log encoding
          logEncoding: ""
          # -- Additional volumeMounts for the controller pod.
          extraVolumeMounts:
          - name: lacework-volume
            mountPath: /var/lib/lacework-backup
          - name: cfgmap
            mountPath: /var/lib/lacework/config
          - name: podinfo
            mountPath: /etc/podinfo
          # - name: aws-iam-token
          #   mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
          #   readOnly: true
          # -- Additional sideCarContainer config - this will also inherit volume mounts from deployment
          sidecarContainer:
            image: docker.io/lacework/datacollector:6.2.0-sidecar
            imagePullPolicy: Always
            name: lw-agent-sidecar
            env:
              - name: LaceworkLogStdout
                value: "yes"
              - name: LaceworkAccessToken
                valueFrom:
                  secretKeyRef:
                    name: lacework-agent-access-token
                    key: agent-access-token
              - name: LW_KUBERNETES_NODENAME
                valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              - name: LW_EXECUTION_ENV
                value: "EKS_FARGATE"

    ```
3. Run helm upgrade command for karpenter
  ```bash
    helm upgrade --install karpenter -n karpenter oci://public.ecr.aws/karpenter/karpenter -f values.yaml --version v0.22.1 --debug --dry-run
  ```
  
 This is a crash with the following error

```bash
history.go:56: [debug] getting history for release karpenter
upgrade.go:139: [debug] preparing upgrade for karpenter
Error: UPGRADE FAILED: template: karpenter/templates/deployment.yaml:117:26: executing "karpenter/templates/deployment.yaml" at <.Values.controller.extraVolumeMounts>: nil pointer evaluating interface {}.controller
helm.go:88: [debug] template: karpenter/templates/deployment.yaml:117:26: executing "karpenter/templates/deployment.yaml" at <.Values.controller.extraVolumeMounts>: nil pointer evaluating interface {}.controller
UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:200
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```

### Resource Specs and Logs

```bash
history.go:56: [debug] getting history for release karpenter
upgrade.go:139: [debug] preparing upgrade for karpenter
Error: UPGRADE FAILED: template: karpenter/templates/deployment.yaml:117:26: executing "karpenter/templates/deployment.yaml" at <.Values.controller.extraVolumeMounts>: nil pointer evaluating interface {}.controller
helm.go:88: [debug] template: karpenter/templates/deployment.yaml:117:26: executing "karpenter/templates/deployment.yaml" at <.Values.controller.extraVolumeMounts>: nil pointer evaluating interface {}.controller
UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:200
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jralph** [comment]
We're also having the same issue. We're unable to deploy a sidecar when using karpenter with fargate. Our use case for this is to be able to collect logs/metrics using Datadog.

**Comment by Flydiverny** [comment]
Something seems to have gone wrong in the helm chart template implementation
https://github.com/aws/karpenter/pull/3143#discussion_r1082004777

**Comment by endriu0** [comment]
Yes - my bad. Sent a PR 3253 now which should fix the issue - please feel free to test it out and make sure it works. Sorry about that - crazy week and didnt spend enough time testing the sidecar.

**Comment by yousafsyed-bg** [comment]
@endriu0 I will test it today and close the issue. Thanks for a prompt resolution

**Comment by yousafsyed-bg** [comment]
@endriu0 I think it's not fixed, how did you test the new chart? can you please add an example?

Plus what is the reason for forcing `extraVolumeMounts` on the sidecars? If I want a volume to be mounted I can specify it within my sidecar configs. Now its a list and I can select multiple sidecars and volume mounts for sidecars assuming there can be only one sidecar

Relevant values and still fails. when upgrading 
```yaml
controller:
  # -- Controller image.
  image: "public.ecr.aws/karpenter/controller:v0.23.0@sha256:40aea3b25a33ff2cb44bdecf0417a2642e2a785b4fd30067634ef8f1bd48383c"
  # -- SecurityContext for the controller container.
  securityContext: {}
  # -- Additional environment variables for the controller pod.
  env: []
  # - name: AWS_REGION
  #   value: eu-west-1

  # -- Resources for the controller pod.
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  # -- Controller outputPaths - default to stdout only
  outputPaths:
    - stdout
  # -- Controller errorOutputPaths - default to stderr only
  errorOutputPaths:
    - stderr
  # -- Controller log level, defaults to the global log level
  logLevel: ""
  # -- Controller log encoding, defaults to the global log encoding
  logEncoding: ""
  # -- Additional volumeMounts for the controller pod.
  extraVolumeMounts:
  - name: aws-iam-token
    mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
    readOnly: true
  # -- Additional sidecarContainer config
  sidecarContainer:
  - image: ubuntu:latest
    imagePullPolicy: Always
    name: sidecar1
  sidecarVolumeMounts: 
  - name: aws-iam-token
    mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
    readOnly: true

```

**Comment by endriu0** [comment]
@yousafsyed-bg The changes did not make it to 0.23.0 release and this is why you cannot get it working with OCI chart. I believe this will have to wait for 0.23.1 for those chart changes to go live.

**Comment by endriu0** [comment]
@yousafsyed-bg https://github.com/aws/karpenter/blob/v0.23.0/charts/karpenter/templates/deployment.yaml - you can see that the last commit is from 2 weeks ago in that version.

**Comment by yousafsyed-bg** [comment]
@endriu0 thanks for the updates, do you when can we expect for 0.23.1 to go live.

Thanks

**Comment by endriu0** [comment]
@yousafsyed-bg Nope, sorry this is up to the karpenter maintainers to establish. Karpenter has a pretty fast release cadence so I wouldn't be surprised if we'll see 0.23.1 by next week.

As for the volume mounts part of your question - it was done so that we automatically get all the deployment extraVolumeMounts added to the sidecar so you do not need to specify in your example `  - name: aws-iam-token` twice - instead it will be picked up from the extraVolumeMounts entry already.

As for specifying the actual volume mounts directly in the sidecar - I thought about it but after quite a few attempts I was not able to merge that with `extraVolumeMounts` entries therefore opted for the second best option I could think off to make it more automagic. 

I am unfortunately OOO whole this week and probably next so cannot spend any more time testing this - if you have any ideas on how to merge those feel free to send a PR for maintainers to check / merge before next release.
