### ISSUE TITLE
Upgrading to v0.27.3 controller.pricing UnrecognizedClientException in China Region

### ISSUE THREAD

**Issue by hitsub2** [aws/karpenter#3871]
### Version

__Karpenter Version:__ v0.27.3

__Kubernetes Version:__ v1.25, v1.21, v1.26
Region: CN-NORTH-1

### Expected Behavior

karpenter updates the price successfully.

### Actual Behavior

Karpenter controller keeps refresh logs:
```
2023-05-10T08:16:44.276Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
```
It is still in function for scaling, but controller repeat those logs.

Full logs

```
2023-05-10T08:12:18.019Z	INFO	controller	Starting workers	{"commit": "d7e22b1-dirty", "controller": "provisioner_metrics", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 1}
2023-05-10T08:12:18.019Z	INFO	controller	Starting workers	{"commit": "d7e22b1-dirty", "controller": "awsnodetemplate", "controllerGroup": "karpenter.k8s.aws", "controllerKind": "AWSNodeTemplate", "worker count": 10}
2023-05-10T08:12:18.019Z	INFO	controller	Starting workers	{"commit": "d7e22b1-dirty", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 10}
2023-05-10T08:12:18.023Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: 2f7ca07f-f03f-5b52-93df-fcaaa41d57bb	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:18.089Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: d60241e9-83fe-5a8c-aff4-1d3cd7dc5665	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:18.219Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: 850ac47c-f75b-557d-8acb-98a9a379c994	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:18.400Z	DEBUG	controller.consistency	discovered instance types	{"commit": "d7e22b1-dirty", "node": "ip-192-168-27-164.cn-north-1.compute.internal", "count": 263}
2023-05-10T08:12:18.471Z	DEBUG	controller.consistency	discovered subnets	{"commit": "d7e22b1-dirty", "node": "ip-192-168-27-164.cn-north-1.compute.internal", "subnets": ["subnet-076f2ecf25a971d30 (cn-north-1a)"]}
2023-05-10T08:12:18.478Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: 8506cc1b-e1c2-5247-a36e-90ceb5e0eeae	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:18.524Z	DEBUG	controller.consistency	discovered offerings for instance types	{"commit": "d7e22b1-dirty", "node": "ip-192-168-6-251.cn-north-1.compute.internal", "zones": ["cn-north-1a"], "instance-type-count": 261, "node-template": ""}
2023-05-10T08:12:18.609Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: f5e12afc-cc76-4b98-8779-c894d1d3fd54; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: cf260a8e-fc65-45d9-982a-112088c957fc	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:18.756Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: e3adf109-b00f-4c47-9800-4472e4fdf847; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 2cc13910-a61f-488a-aace-bd295df8bc2b	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:18.905Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 6524f81d-0ad0-422b-a412-f5844ca1c950; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 4a619458-f95c-4681-9213-981b567f01aa	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:18.997Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: 11d46f30-c7b4-5f8e-9dcd-33e593960367	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:19.055Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 8063d310-f36b-4ec3-af10-cb06afc4fa4e; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: c1fe8a57-a1ba-46cd-aa32-a92a6b02c69d	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:19.210Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: f12b0a20-bcb6-48bd-a4c9-8b46ad4a1ea1; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: c6743bcb-2be0-4f49-a744-87b4aa7903ba	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:19.368Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: a317a962-a4da-4235-9085-e21f366473ed; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: b2d69cbc-9fa5-4d2d-aa71-6e9f5816ac26	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:19.542Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: b800d462-9493-4692-ae6e-6d6922d74f24; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 5748af38-910f-4b01-9025-d8c94ceea2dd	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:19.748Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 114ea1a0-5a03-45e6-b898-7ced35a81b15; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 9362c838-7fc2-4001-a0b1-2ab6a58303eb	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:20.018Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 365ed81b-a76c-49ce-b44c-4f5b2e2a0050; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: d965879a-4fcc-482f-a2c3-ac7b0e847455	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:20.028Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: d6b40898-8bf4-5d2b-bf02-544ddfd081c2	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:20.417Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 9dc0fff0-e9ce-418e-8f87-b820d007f63e; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 9ef921b2-58df-4f38-a722-b16409081c7e	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:21.072Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 1f80f2f1-6b6c-431e-b9bb-0c7adebef0e4; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: be3daa93-af35-4f50-8419-a5f06d7b8b90	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:22.081Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: ec40134e-c0b3-500d-8256-4f9b94950ce4	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:22.239Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 6443cd48-fe10-486d-a97d-cfb43793b035; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 11eb1836-a750-443a-a9cf-c40f15327d99	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:24.434Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: c37d43d5-e772-4705-a1ba-e35a1ba3d8a6; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: d3c41a9f-d1bd-4ff7-88d0-5690a971ba7f	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:26.184Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: c3df47c4-cdf7-56b2-a823-1b1199ddba5b	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:28.677Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 6f144ac9-b3d3-4507-b6ff-4fd66e0345e8; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: f108b5a9-f607-4f5c-83fa-2a12ec55addd	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:34.383Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: d2affa40-f065-591c-8c25-a695a45785f5	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:37.032Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: f9f89d29-577b-4d09-bc9d-bd06704ac39b; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: cbb1f7ed-cd85-4750-b5da-482efe487329	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:50.773Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: 8c1ef961-e0c7-504c-a8e6-a5b4b485bca5	{"commit": "d7e22b1-dirty"}
2023-05-10T08:12:53.563Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 6fbd6680-2a7d-4302-ae7d-0264cd6b112d; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: f7a21917-068a-4790-870a-1fe7bc786640	{"commit": "d7e22b1-dirty"}
2023-05-10T08:13:23.547Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: f4d76991-f208-579f-a23b-3544a66bfb76	{"commit": "d7e22b1-dirty"}
2023-05-10T08:13:26.478Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: bbbe0de2-2afe-4186-a960-f28b7648c766; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: cb454bf0-823c-44f3-9e12-525c73dad296	{"commit": "d7e22b1-dirty"}
2023-05-10T08:14:29.122Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: c2eadd1f-d7cf-51b3-84ea-81ca836a1da4	{"commit": "d7e22b1-dirty"}
2023-05-10T08:14:32.589Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 03a62497-ec30-41c7-901f-53a282794d13; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 25f2d278-9342-4a20-9dbb-ca43aa26fd75	{"commit": "d7e22b1-dirty"}
2023-05-10T08:16:40.220Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: e73d12ab-1eb4-5515-be3d-4e7e4b9c5d45	{"commit": "d7e22b1-dirty"}
2023-05-10T08:16:44.276Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: c60bdf32-d2ca-4be4-84a6-75c24723c24d; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 0c105216-0606-4736-8f0e-af5a503a8d81	{"commit": "d7e22b1-dirty"}
2023-05-10T08:21:02.384Z	ERROR	controller.interruption	getting messages from queue, discovering queue url, fetching queue url, AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
	status code: 400, request id: ef7dc97d-bb9b-5796-ab7c-95a8edb5f49c	{"commit": "d7e22b1-dirty"}
2023-05-10T08:21:07.091Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 4f351401-6f02-4db0-acf3-4b3fe6926722; UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: f9e21558-b3ad-4e76-b023-ed82dcdbec8f	{"commit": "d7e22b1-dirty"}
```

### Steps to Reproduce the Problem

Upgrade from older version, like upgrade from v0.18.0 to v0.27.3

### Resource Specs and Logs

Karpenter controller keeps refresh logs:
```
2023-05-10T08:16:44.276Z	ERROR	controller.pricing	UnrecognizedClientException: The security token included in the request is invalid
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ellistarn** [comment]
Looks like your credentials are misconfigured for your pod: https://stackoverflow.com/questions/56835781/unrecognizedclientexception-the-security-token-included-in-the-request-is-inval. How are you configuring this?

**Comment by hitsub2** [comment]
It is the karpenter controller pod generates the logs, the service account configuration is valid.

**Comment by ellistarn** [comment]
How are you configuring AWS credential for your Kubernetes service account? IRSA? Kube2iam? Something else?

**Comment by faithgithub** [comment]
> How are you configuring AWS credential for your Kubernetes service account? IRSA? Kube2iam? Something else?

I meet the same question;the service account configuration is valid.

**Comment by Chen188** [comment]
The pricing endpoint seems not available in China regions(cn-north-1 and cn-northwest-1).

**Comment by hitsub2** [comment]
> The pricing endpoint seems not available in China regions(cn-north-1 and cn-northwest-1).

It has been fixed in this [pull](https://github.com/aws/karpenter/pull/2866). This issue seems to be another issue.

**Comment by hitsub2** [comment]
> > How are you configuring AWS credential for your Kubernetes service account? IRSA? Kube2iam? Something else?
> 
> I meet the same question;the service account configuration is valid.

@faithgithub  Would you provide more details?

**Comment by sergkondr** [comment]
Hello guys! The issue still exists, do you have any updates or any thoughts?

**Comment by tzneal** [comment]
You can use the settings documented [here](https://karpenter.sh/docs/concepts/settings/) and set `aws.isolatedVPC` which will disable the pricing lookups and remove the error messages.  Karpenter will be updated to support the any newly available pricing endpoints when they are made available.

**Comment by sergkondr** [comment]
> You can use the settings documented [here](https://karpenter.sh/docs/concepts/settings/) and set `aws.isolatedVPC` which will disable the pricing lookups and remove the error messages. Karpenter will be updated to support the any newly available pricing endpoints when they are made available.

Thank you, it works for me!
