### ISSUE TITLE
Karpenter in unconsolidatable state when there are any unschedulable pods

### ISSUE THREAD

**Issue by rkilingr** [aws/karpenter#4533]
## **Observed Behavior**:
When there are any unschedulable pods sitting anywhere in the cluster, karpenter fails consolidate the existing pods towards right sized instance types. This happens even when the unschedulable pods are unrelated(managed by CA, Node Group) and would never schedule on the karpenter provisioned node due to different `tolerations` and `nodeSelector`

## **Expected Behavior**:
Shouldn't karpenter ignore unrelated pods being unschedulable when consolidating pods of a particular provisioner?
### Example:
- Unschedulable pods:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fake-sample-service-usw2-dev2
  labels:
    name: fake-sample-service-usw2-dev2
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: fake-sample-service-usw2-dev2-default
spec:
  limits:
    resources:
      cpu: 20
  consolidation:
    enabled: true
  taints:
    - key: ig/fakesampleserviceusw2dev2default
      effect: NoSchedule
    - key: ig/fakesampleserviceusw2dev2default
      effect: NoExecute
  labels:
    node.kubernetes.io/instancegroup: fake-sample-service-usw2-dev2-default
    node.kubernetes.io/role: fake-sample-service-usw2-dev2-default
  providerRef:
    name: custom-family
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ['m','c','r']
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ['5']
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-sample-service
  name: fake-sample-service-deployment
  namespace: fake-sample-service-usw2-dev2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fake-sample-service
  template:
    metadata:
      labels:
        app: fake-sample-service
    spec:
      tolerations:
        - key: ig/fakesampleserviceusw2dev2default
      nodeSelector:
        node.kubernetes.io/instancegroup: fake-sample-service-usw2-dev2-default
      containers:
        - image: nginx:1.14.2
          name: app
          resources:  {"limits":{"cpu":"30","memory":"10Gi"},"requests":{"cpu":"30","memory":"10Gi"}}
```
- Pods that are supposed to consolidate:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fake-sample-service-usw2-dev
  labels:
    name: fake-sample-service-usw2-dev
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: fake-sample-service-usw2-dev-default
spec:
  consolidation:
    enabled: true
  taints:
    - key: ig/fakesampleserviceusw2devdefault
      effect: NoSchedule
    - key: ig/fakesampleserviceusw2devdefault
      effect: NoExecute
  labels:
    node.kubernetes.io/instancegroup: fake-sample-service-usw2-dev-default
    node.kubernetes.io/role: fake-sample-service-usw2-dev-default
  providerRef:
    name: custom-family
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ['m','c','r']
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ['5']
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-sample-service
  name: fake-sample-service-deployment
  namespace: fake-sample-service-usw2-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-sample-service
  template:
    metadata:
      labels:
        app: fake-sample-service
    spec:
      tolerations:
        - key: ig/fakesampleserviceusw2dev2default
      nodeSelector:
        node.kubernetes.io/instancegroup: fake-sample-service-usw2-dev2-default
      containers:
        - image: nginx:1.14.2
          name: app
          resources:  {"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}}
```

Observation is a `c6a.4xlarge` instance is created and then the nodes have the following event preventing it from consolidation:
```shell
Normal   Unconsolidatable         8m58s              karpenter        not all pods would schedule, fake-sample-service-usw2-dev2/fake-sample-service-deployment-7fb449d879-q95hj => incompatible with provisioner "custom-provideref", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, incompatible requirements, key node.kubernetes.io/instancegroup, node.kubernetes.io/instancegroup In [fake-sample-service-usw2-dev2-default] not in node.kubernetes.io/instancegroup In [knodes]; incompatible with provisioner "fake-sample-service-usw2-dev2-default", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, no instance type satisfied resources {"cpu":"30490m","memory":"11675723008","pods":"10"} and requirements karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >5, karpenter.sh/capacity-type In [on-demand], karpenter.sh/provisioner-name In [fake-sample-service-usw2-dev2-default], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node.kubernetes.io/instancegroup In [fake-sample-service-usw2-dev2-default], node.kubernetes.io/role In [fake-sample-service-usw2-dev2-default] (no instance type has enough resources); incompatible with provisioner "fake-sample-service-usw2-dev-default", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, did not tolerate ig/fakesampleserviceusw2devdefault=:NoSchedule; did not tolerate ig/fakesampleserviceusw2devdefault=:NoExecute fake-sample-service-usw2-dev2/fake-sample-service-deployment-7fb449d879-qpcz7 => incompatible with provisioner "custom-provideref", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, incompatible requirements, key node.kubernetes.io/instancegroup, node.kubernetes.io/instancegroup In [fake-sample-service-usw2-dev2-default] not in node.kubernetes.io/instancegroup In [knodes]; incompatible with provisioner "fake-sample-service-usw2-dev2-default", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, no instance type satisfied resources {"cpu":"30490m","memory":"11675723008","pods":"10"} and requirements karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >5, karpenter.sh/capacity-type In [on-demand], karpenter.sh/provisioner-name In [fake-sample-service-usw2-dev2-default], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node.kubernetes.io/instancegroup In [fake-sample-service-usw2-dev2-default], node.kubernetes.io/role In [fake-sample-service-usw2-dev2-default] (no instance type has enough resources); incompatible with provisioner "fake-sample-service-usw2-dev-default", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, did not tolerate ig/fakesampleserviceusw2devdefault=:NoSchedule; did not tolerate ig/fakesampleserviceusw2devdefault=:NoExecute fake-sample-service-usw2-dev2/fake-sample-service-deployment-7fb449d879-dvrp4 => incompatible with provisioner "custom-provideref", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, incompatible requirements, key node.kubernetes.io/instancegroup, node.kubernetes.io/instancegroup In [fake-sample-service-usw2-dev2-default] not in node.kubernetes.io/instancegroup In [knodes]; incompatible with provisioner "fake-sample-service-usw2-dev2-default", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, no instance type satisfied resources {"cpu":"30490m","memory":"11675723008","pods":"10"} and requirements karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >5, karpenter.sh/capacity-type In [on-demand], karpenter.sh/provisioner-name In [fake-sample-service-usw2-dev2-default], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node.kubernetes.io/instancegroup In [fake-sample-service-usw2-dev2-default], node.kubernetes.io/role In [fake-sample-service-usw2-dev2-default] (no instance type has enough resources); incompatible with provisioner "fake-sample-service-usw2-dev-default", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, did not tolerate ig/fakesampleserviceusw2devdefault=:NoSchedule; did not tolerate ig/fakesampleserviceusw2devdefault=:NoExecute fake-sample-service-usw2-dev2/fake-sample-service-deployment-7fb449d879-nbpv6 => incompatible with provisioner "custom-provideref", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, incompatible requirements, key node.kubernetes.io/instancegroup, node.kubernetes.io/instancegroup In [fake-sample-service-usw2-dev2-default] not in node.kubernetes.io/instancegroup In [knodes]; incompatible with provisioner "fake-sample-service-usw2-dev2-default", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, no instance type satisfied resources {"cpu":"30490m","memory":"11675723008","pods":"10"} and requirements karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-generation Exists >5, karpenter.sh/capacity-type In [on-demand], karpenter.sh/provisioner-name In [fake-sample-service-usw2-dev2-default], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], node.kubernetes.io/instancegroup In [fake-sample-service-usw2-dev2-default], node.kubernetes.io/role In [fake-sample-service-usw2-dev2-default] (no instance type has enough resources); incompatible with provisioner "fake-sample-service-usw2-dev-default", daemonset overhead={"cpu":"490m","memory":"938304768","pods":"9"}, did not tolerate ig/fakesampleserviceusw2devdefault=:NoSchedule; did not tolerate ig/fakesampleserviceusw2devdefault=:NoExecute
```

whereas without the unschedulable pods, it consolidates the node to `c6a.xlarge`
## **Versions**:
- Chart Version: v0.29.2
- Kubernetes Version (`kubectl version`): 
  ```shell
  Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.16", 
  GitCommit:"51e33fadff13065ae5518db94e84598293965939", GitTreeState:"clean", BuildDate:"2023-07-19T12:26:21Z", 
  GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/amd64"}
  Kustomize Version: v4.5.4
  Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.16-eks-2d98532", 
  GitCommit:"af930c12e26ef9d1e8fac7e3532ff4bcc1b2b509", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:47Z", 
  GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
  ```

## Notes
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you upgrade to `v0.30.0`? This issue should have been fixed by: https://github.com/aws/karpenter-core/pull/458

**Comment by rkilingr** [comment]
@jonathan-innis Thanks! I was able to verify the issue is fixed.

But still I don't get one thing, why does it provision `c6a.4xlarge` in the beginning and then consolidate to `c6a.xlarge`? The pod is able to fit in `c6a.xlarge` itself fine

**Comment by jonathan-innis** [comment]
Hmm, can you share the logs from where that decision was made? Can you also share the `AWSNodeTemplate` that you are referencing in the `Provisioner`?

**Comment by rkilingr** [comment]
Sure!

- Logs:
  ```shell
  2023-08-31T07:58:59.623Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "34d50bf-dirty", "pods": 5}
  2023-08-31T07:58:59.623Z	INFO	controller.provisioner	computed new machine(s) to fit pod(s)	{"commit": "34d50bf-dirty", "machines": 1, "pods": 1}
  2023-08-31T07:58:59.643Z	INFO	controller.provisioner	created machine	{"commit": "34d50bf-dirty", "provisioner": "fake-sample-service-usw2-dev-default", "requests": {"cpu":"2490m","memory":"5233272064","pods":"10"}, "instance-types": "c6a.12xlarge, c6a.16xlarge, c6a.24xlarge, c6a.2xlarge, c6a.4xlarge and 95 other(s)"}
  2023-08-31T07:58:59.701Z	DEBUG	controller.machine.lifecycle	discovered launch template	{"commit": "34d50bf-dirty", "machine": "fake-sample-service-usw2-dev-default-k7zrt", "provisioner": "fake-sample-service-usw2-dev-default", "launch-template-name": "karpenter.k8s.aws/4660582070146404941"}
  2023-08-31T07:59:00.214Z	DEBUG	controller.deprovisioning	waiting on cluster sync	{"commit": "34d50bf-dirty"}
  2023-08-31T07:59:01.214Z	DEBUG	controller.deprovisioning	waiting on cluster sync	{"commit": "34d50bf-dirty"}
  2023-08-31T07:59:01.384Z	INFO	controller.machine.lifecycle	launched machine	{"commit": "34d50bf-dirty", "machine": "fake-sample-service-usw2-dev-default-k7zrt", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2c/i-0b47da5be0f2ed920", "instance-type": "c6a.4xlarge", "zone": "us-west-2c", "capacity-type": "on-demand", "allocatable": {"cpu":"15890m","ephemeral-storage":"122621316300","memory":"27381Mi","pods":"234"}}
  ```
- AWSNodeTemplate:
  ```yaml
  apiVersion: karpenter.k8s.aws/v1alpha1
  kind: AWSNodeTemplate
  metadata:
    name: custom-family
  spec:
    amiFamily: Custom
    amiSelector:
      aws-ids: ami-***
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          encrypted: false
          volumeSize: 128Gi
          volumeType: gp2
    instanceProfile: ***
    securityGroupSelector:
      aws-ids: ***
    subnetSelector:
      aws-ids: ***
    userData: >-
      MIME-Version: 1.0

      Content-Type: multipart/mixed; boundary="BOUNDARY"

      --BOUNDARY

      Content-Type: text/x-shellscript; charset="us-ascii"

      #!/bin/bash

      ******

      set -o xtrace

      /etc/eks/bootstrap.sh *** --b64-cluster-ca
      ***
      --apiserver-endpoint
      ***
      --dns-cluster-ip 172.20.0.10 --kubelet-extra-args
      '--node-labels=node.kubernetes.io/instancegroup=knodes,node.kubernetes.io/role=knodes
      --register-with-taints= --container-log-max-files=5
      --container-log-max-size=50Mi --container-runtime=remote
      --container-runtime-endpoint=unix:///run/containerd/containerd.sock
      --eviction-hard=memory.available<300Mi,nodefs.available<5%,nodefs.inodesFree<3%,imagefs.available<5%,imagefs.inodesFree<3%
      --eviction-max-pod-grace-period=-1
      --eviction-soft=memory.available<500Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
      --eviction-soft-grace-period=memory.available=30s,nodefs.available=30s,nodefs.inodesFree=30s,imagefs.available=30s,imagefs.inodesFree=30s
      --pods-per-core=10 --resolv-conf= --system-reserved=memory=1.5Gi --v=2'

      set +o xtrace

      --BOUNDARY--
  ```
I guess the above is enough? Or let me know if you need anything more

**Comment by garvinp-stripe** [comment]
Do you have the logs from deprovisioning? Also the spec of the pod that landed on that node

**Comment by bwagner5** [comment]
It does look like the resource requests should have fit on a c6a.xlarge to begin with:

```
## From Logs w/ memory converted to something more readable
"requests": {"cpu":"2490m","memory":"4.87Gi","pods":"10"},
## c6a.xlarge allocatable
"allocatable": {"cpu":"3920m","memory":"6.43Gi","pods":"58"},
```

I can also see that the c6a.xlarge was filtered out by Karpenter, not EC2. I'm not sure what would cause that to happen. Can you post more of the logs in one blob so we can check what was going on around this time?

**Comment by rkilingr** [comment]
Here is the full set of logs:
```shell
2023-09-08T05:11:36.365Z        DEBUG   Successfully created the logger.
2023-09-08T05:11:36.365Z        DEBUG   Logging level set to: debug
2023-09-08T05:11:39.169Z        DEBUG   controller      discovered region       {"commit": "637a642", "region": "us-west-2"}
2023-09-08T05:11:39.169Z        DEBUG   controller      discovered cluster endpoint     {"commit": "637a642", "cluster-endpoint": "https://***.***.us-west-2.eks.amazonaws.com"}
2023-09-08T05:11:39.176Z        DEBUG   controller      discovered kube dns     {"commit": "637a642", "kube-dns-ip": "172.20.0.10"}
2023-09-08T05:11:39.177Z        DEBUG   controller      discovered version      {"commit": "637a642", "version": "v0.30.0"}
2023-09-08T05:11:39.177Z        DEBUG   controller      Registering 1 clients   {"commit": "637a642"}
2023-09-08T05:11:39.177Z        DEBUG   controller      Registering 2 informer factories        {"commit": "637a642"}
2023-09-08T05:11:39.177Z        DEBUG   controller      Registering 3 informers {"commit": "637a642"}
2023-09-08T05:11:39.177Z        DEBUG   controller      Registering 5 controllers       {"commit": "637a642"}
2023-09-08T05:11:39.177Z        INFO    controller      Starting server {"commit": "637a642", "path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
2023-09-08T05:11:39.177Z        INFO    controller      Starting server {"commit": "637a642", "kind": "health probe", "addr": "[::]:8081"}
2023-09-08T05:11:39.278Z        INFO    controller      attempting to acquire leader lease addon-karpenter-ns/karpenter-leader-election...
        {"commit": "637a642"}
2023-09-08T05:11:39.315Z        INFO    controller      Starting informers...   {"commit": "637a642"}
2023-09-08T05:11:54.479Z        INFO    controller      successfully acquired lease addon-karpenter-ns/karpenter-leader-election
        {"commit": "637a642"}
2023-09-08T05:11:54.479Z        INFO    controller.provisioner  starting controller     {"commit": "637a642"}
2023-09-08T05:11:54.480Z        INFO    controller.deprovisioning       starting controller     {"commit": "637a642"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "daemonset", "controllerGroup": "apps", "controllerKind": "DaemonSet", "source": "kind source: *v1.DaemonSet"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "daemonset", "controllerGroup": "apps", "controllerKind": "DaemonSet"}
2023-09-08T05:11:54.480Z        DEBUG   controller.deprovisioning       waiting on cluster sync {"commit": "637a642"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "provisioner_trigger", "controllerGroup": "", "controllerKind": "Pod", "source": "kind source: *v1.Pod"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "provisioner_trigger", "controllerGroup": "", "controllerKind": "Pod"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "pod_state", "controllerGroup": "", "controllerKind": "Pod", "source": "kind source: *v1.Pod"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "pod_state", "controllerGroup": "", "controllerKind": "Pod"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "provisioner.hash", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "source": "kind source: *v1alpha5.Provisioner"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "provisioner.hash", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "source": "kind source: *v1.Node"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "machine-state", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1alpha5.Machine"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "machine-state", "controllerGroup": "karpenter.sh", "controllerKind": "Machine"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "provisioner_state", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "source": "kind source: *v1alpha5.Provisioner"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "provisioner_state", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "pod_metrics", "controllerGroup": "", "controllerKind": "Pod", "source": "kind source: *v1.Pod"}
2023-09-08T05:11:54.480Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "pod_metrics", "controllerGroup": "", "controllerKind": "Pod"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "termination", "controllerGroup": "", "controllerKind": "Node", "source": "kind source: *v1.Node"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "termination", "controllerGroup": "", "controllerKind": "Node"}
2023-09-08T05:11:54.481Z        INFO    controller.metric_scraper       starting controller     {"commit": "637a642"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "provisioner_metrics", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "source": "kind source: *v1alpha5.Provisioner"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "provisioner_metrics", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "consistency", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1alpha5.Machine"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "consistency", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1.Node"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "consistency", "controllerGroup": "karpenter.sh", "controllerKind": "Machine"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "source": "kind source: *v1alpha5.Provisioner"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "source": "kind source: *v1alpha5.Machine"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "source": "kind source: *v1.Node"}
2023-09-08T05:11:54.481Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner"}
2023-09-08T05:11:54.481Z        INFO    controller.machine.garbagecollection    starting controller     {"commit": "637a642"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "machine.lifecycle", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1alpha5.Machine"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "machine.lifecycle", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1.Node"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "machine.lifecycle", "controllerGroup": "karpenter.sh", "controllerKind": "Machine"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "machine.disruption", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1alpha5.Machine"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "machine.disruption", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1alpha5.Provisioner"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "machine.disruption", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1.Node"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "machine.disruption", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1.Pod"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "machine.disruption", "controllerGroup": "karpenter.sh", "controllerKind": "Machine"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "machine.termination", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1alpha5.Machine"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "machine.termination", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "source": "kind source: *v1.Node"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "machine.termination", "controllerGroup": "karpenter.sh", "controllerKind": "Machine"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "awsnodetemplate", "controllerGroup": "karpenter.k8s.aws", "controllerKind": "AWSNodeTemplate", "source": "kind source: *v1alpha1.AWSNodeTemplate"}
2023-09-08T05:11:54.482Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "awsnodetemplate", "controllerGroup": "karpenter.k8s.aws", "controllerKind": "AWSNodeTemplate"}
2023-09-08T05:11:54.486Z        INFO    controller      Starting EventSource    {"commit": "637a642", "controller": "lease.garbagecollection", "controllerGroup": "coordination.k8s.io", "controllerKind": "Lease", "source": "kind source: *v1.Lease"}
2023-09-08T05:11:54.486Z        INFO    controller      Starting Controller     {"commit": "637a642", "controller": "lease.garbagecollection", "controllerGroup": "coordination.k8s.io", "controllerKind": "Lease"}
2023-09-08T05:11:54.486Z        INFO    controller.machine.garbagecollection    starting controller     {"commit": "637a642"}
2023-09-08T05:11:54.487Z        INFO    controller.machine.link starting controller     {"commit": "637a642"}
2023-09-08T05:11:54.487Z        INFO    controller.pricing      starting controller     {"commit": "637a642"}
2023-09-08T05:11:54.487Z        INFO    controller.interruption starting controller     {"commit": "637a642"}
2023-09-08T05:11:54.487Z        DEBUG   controller.interruption watching interruption queue     {"commit": "637a642", "queue": "rkilingar-eks-dev-k8s-karpenter"}
2023-09-08T05:11:54.539Z        DEBUG   controller      hydrated launch template cache  {"commit": "637a642", "tag-key": "karpenter.k8s.aws/cluster", "tag-value": "rkilingar-eks-dev-k8s", "count": 0}
2023-09-08T05:11:54.581Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "node_state", "controllerGroup": "", "controllerKind": "Node", "worker count": 10}
2023-09-08T05:11:54.581Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "daemonset", "controllerGroup": "apps", "controllerKind": "DaemonSet", "worker count": 10}
2023-09-08T05:11:54.581Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "provisioner_trigger", "controllerGroup": "", "controllerKind": "Pod", "worker count": 10}
2023-09-08T05:11:54.581Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "pod_state", "controllerGroup": "", "controllerKind": "Pod", "worker count": 10}
2023-09-08T05:11:54.581Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "pod_metrics", "controllerGroup": "", "controllerKind": "Pod", "worker count": 1}
2023-09-08T05:11:54.581Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "machine-state", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "worker count": 10}
2023-09-08T05:11:54.582Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "termination", "controllerGroup": "", "controllerKind": "Node", "worker count": 100}
2023-09-08T05:11:54.582Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "consistency", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "worker count": 10}
2023-09-08T05:11:54.582Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "machine.lifecycle", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "worker count": 1000}
2023-09-08T05:11:54.586Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "machine.termination", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "worker count": 100}
2023-09-08T05:11:54.586Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "lease.garbagecollection", "controllerGroup": "coordination.k8s.io", "controllerKind": "Lease", "worker count": 10}
2023-09-08T05:11:54.682Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "provisioner_state", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 10}
2023-09-08T05:11:54.682Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "provisioner.hash", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 10}
2023-09-08T05:11:54.682Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 10}
2023-09-08T05:11:54.682Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "provisioner_metrics", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 1}
2023-09-08T05:11:54.683Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "machine.disruption", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "worker count": 10}
2023-09-08T05:11:54.683Z        INFO    controller      Starting workers        {"commit": "637a642", "controller": "awsnodetemplate", "controllerGroup": "karpenter.k8s.aws", "controllerKind": "AWSNodeTemplate", "worker count": 10}
2023-09-08T05:11:54.786Z        DEBUG   controller.awsnodetemplate      discovered subnets      {"commit": "637a642", "awsnodetemplate": "custom-family", "subnets": ["subnet-*** (us-west-2c)", "subnet-*** (us-west-2b)", "subnet-*** (us-west-2a)"]}
2023-09-08T05:11:54.816Z        DEBUG   controller.pricing      updated spot pricing with instance types and offerings  {"commit": "637a642", "instance-type-count": 702, "offering-count": 2421}
2023-09-08T05:11:54.947Z        DEBUG   controller.awsnodetemplate      discovered security groups      {"commit": "637a642", "awsnodetemplate": "custom-family", "security-groups": ["sg-033ba0c88612bdd2f"]}
2023-09-08T05:11:55.006Z        DEBUG   controller.awsnodetemplate      discovered amis {"commit": "637a642", "awsnodetemplate": "custom-family", "ids": "ami-0e1a2de12a7c796d7", "count": 1}
2023-09-08T05:11:56.376Z        DEBUG   controller.deprovisioning       discovered instance types       {"commit": "637a642", "count": 705}
2023-09-08T05:11:56.529Z        DEBUG   controller.deprovisioning       discovered offerings for instance types {"commit": "637a642", "zones": ["us-west-2a", "us-west-2b", "us-west-2c"], "instance-type-count": 706, "node-template": "custom-family"}
2023-09-08T05:11:56.703Z        DEBUG   controller.pricing      updated on-demand pricing       {"commit": "637a642", "instance-type-count": 707}
2023-09-08T05:12:04.333Z        DEBUG   controller.provisioner  55 out of 704 instance types were excluded because they would breach limits     {"commit": "637a642", "provisioner": "custom-provideref"}
2023-09-08T05:12:04.342Z        INFO    controller.provisioner  found provisionable pod(s)      {"commit": "637a642", "pods": 1}
2023-09-08T05:12:04.342Z        INFO    controller.provisioner  computed new machine(s) to fit pod(s)   {"commit": "637a642", "machines": 1, "pods": 1}
2023-09-08T05:12:04.367Z        INFO    controller.provisioner  created machine {"commit": "637a642", "provisioner": "fake-sample-service-usw2-dev-default", "machine": "fake-sample-service-usw2-dev-default-r9xzj", "requests": {"cpu":"2490m","memory":"5233272064","pods":"10"}, "instance-types": "c6a.12xlarge, c6a.16xlarge, c6a.24xlarge, c6a.2xlarge, c6a.4xlarge and 95 other(s)"}
2023-09-08T05:12:04.581Z        DEBUG   controller.machine.lifecycle    created launch template {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-r9xzj", "provisioner": "fake-sample-service-usw2-dev-default", "launch-template-name": "karpenter.k8s.aws/3017482902690889200", "id": "lt-003df5206b6c0968f"}
2023-09-08T05:12:06.407Z        INFO    controller.machine.lifecycle    launched machine        {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-r9xzj", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2c/i-057c88a8cb630a08a", "instance-type": "c6a.4xlarge", "zone": "us-west-2c", "capacity-type": "on-demand", "allocatable": {"cpu":"15890m","ephemeral-storage":"122621316300","memory":"27381Mi","pods":"234"}}
2023-09-08T05:14:09.186Z        DEBUG   controller.machine.lifecycle    registered machine      {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-r9xzj", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2c/i-057c88a8cb630a08a", "node": "ip-**-**-***-***.us-west-2.compute.internal"}
2023-09-08T05:15:13.240Z        DEBUG   controller.machine.lifecycle    initialized machine     {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-r9xzj", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2c/i-057c88a8cb630a08a", "node": "ip-**-**-***-***.us-west-2.compute.internal"}
2023-09-08T05:15:42.083Z        INFO    controller.deprovisioning       deprovisioning via consolidation replace, terminating 1 machines ip-**-**-***-***.us-west-2.compute.internal/c6a.4xlarge/on-demand and replacing with on-demand machine from types r6i.xlarge, r6a.2xlarge, r6id.xlarge, m6a.2xlarge, c6in.xlarge and 26 other(s) {"commit": "637a642"}
2023-09-08T05:15:42.129Z        INFO    controller.deprovisioning       created machine {"commit": "637a642", "provisioner": "fake-sample-service-usw2-dev-default", "machine": "fake-sample-service-usw2-dev-default-lxsf9", "requests": {"cpu":"2490m","memory":"5233272064","pods":"10"}, "instance-types": "c6a.2xlarge, c6a.xlarge, c6i.2xlarge, c6i.xlarge, c6id.2xlarge and 26 other(s)"}
2023-09-08T05:15:42.281Z        DEBUG   controller.machine.lifecycle    discovered subnets      {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-lxsf9", "provisioner": "fake-sample-service-usw2-dev-default", "subnets": ["subnet-*** (us-west-2c)", "subnet-*** (us-west-2b)", "subnet-*** (us-west-2a)"]}
2023-09-08T05:15:42.494Z        DEBUG   controller.machine.lifecycle    discovered launch template      {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-lxsf9", "provisioner": "fake-sample-service-usw2-dev-default", "launch-template-name": "karpenter.k8s.aws/3017482902690889200"}
2023-09-08T05:15:44.281Z        INFO    controller.machine.lifecycle    launched machine        {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-lxsf9", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2a/i-08c7ee0a00f459e37", "instance-type": "c6a.xlarge", "zone": "us-west-2a", "capacity-type": "on-demand", "allocatable": {"cpu":"3920m","ephemeral-storage":"122621316300","memory":"6584Mi","pods":"58"}}
2023-09-08T05:16:55.103Z        DEBUG   controller.awsnodetemplate      discovered subnets      {"commit": "637a642", "awsnodetemplate": "custom-family", "subnets": ["subnet-*** (us-west-2c)", "subnet-*** (us-west-2b)", "subnet-*** (us-west-2a)"]}
2023-09-08T05:17:07.482Z        DEBUG   controller.machine.lifecycle    registered machine      {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-lxsf9", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2a/i-08c7ee0a00f459e37", "node": "ip-**-**-***-***.us-west-2.compute.internal"}
2023-09-08T05:17:54.922Z        DEBUG   controller.machine.lifecycle    initialized machine     {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-lxsf9", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2a/i-08c7ee0a00f459e37", "node": "ip-**-**-***-***.us-west-2.compute.internal"}
2023-09-08T05:17:56.476Z        INFO    controller.termination  cordoned node   {"commit": "637a642", "node": "ip-**-**-***-***.us-west-2.compute.internal"}
2023-09-08T05:17:57.994Z        INFO    controller.termination  deleted node    {"commit": "637a642", "node": "ip-**-**-***-***.us-west-2.compute.internal"}
2023-09-08T05:17:58.244Z        INFO    controller.machine.termination  deleted machine {"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-r9xzj", "provisioner": "fake-sample-service-usw2-dev-default", "node": "ip-**-**-***-***.us-west-2.compute.internal", "provider-id": "aws:///us-west-2c/i-057c88a8cb630a08a"}
```

**Comment by garvinp-stripe** [comment]
I wonder if it is because scheduling it considers unschedulable pods but consolidation doesn't. That means that it choose a bigger node because it thinks it can make the unschedulable + new pod fit it in. With v0.30.0 it will then consolidate ignoring the unschedulable pod.

**Comment by njtran** [comment]
@garvinp-stripe this is a good thought. @rkilingr can you share the specs/resource requests of the unschedulable pods in your cluster? I know you said the issue was fixed, but if you have some leftover pods that are permanently unschedulable, we can see if the resource requests of those pods is similar to the size of the differential from a `c6a.4xlarge` to any of the chosen replacements in `from types r6i.xlarge, r6a.2xlarge, r6id.xlarge, m6a.2xlarge, c6in.xlarge and 26 other(s)`.  If so, that would help validate @garvinp-stripe 's theory.

**Comment by rkilingr** [comment]
@njtran @garvinp-stripe Since consolidation is working fine since v0.30.0, I had tested again without the `Pending` pods and the issue is still there.
Attaching logs again:
```
2023-09-21T13:14:01.649Z	DEBUG	controller.provisioner	58 out of 724 instance types were excluded because they would breach limits	{"commit": "637a642", "provisioner": "custom-provideref"}
2023-09-21T13:14:01.659Z	INFO	controller.provisioner	found provisionable pod(s)	{"commit": "637a642", "pods": 1}
2023-09-21T13:14:01.659Z	INFO	controller.provisioner	computed new machine(s) to fit pod(s)	{"commit": "637a642", "machines": 1, "pods": 1}
2023-09-21T13:14:01.680Z	INFO	controller.provisioner	created machine	{"commit": "637a642", "provisioner": "fake-sample-service-usw2-dev-default", "machine": "fake-sample-service-usw2-dev-default-72mzr", "requests": {"cpu":"2490m","memory":"5233272064","pods":"10"}, "instance-types": "c6a.12xlarge, c6a.16xlarge, c6a.2xlarge, c6a.4xlarge, c6a.8xlarge and 95 other(s)"}
2023-09-21T13:14:01.847Z	DEBUG	controller.machine.lifecycle	discovered subnets	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-72mzr", "provisioner": "fake-sample-service-usw2-dev-default", "subnets": ["subnet-0282303dcb0702609 (us-west-2c)", "subnet-0650553d00f415a5c (us-west-2b)", "subnet-0270dd49606120b3b (us-west-2a)"]}
2023-09-21T13:14:03.939Z	DEBUG	controller.deprovisioning	waiting on cluster sync	{"commit": "637a642"}
2023-09-21T13:14:04.047Z	INFO	controller.machine.lifecycle	launched machine	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-72mzr", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2a/i-***", "instance-type": "c6a.4xlarge", "zone": "us-west-2a", "capacity-type": "on-demand", "allocatable": {"cpu":"15890m","ephemeral-storage":"122621316300","memory":"27381Mi","pods":"234"}}
2023-09-21T13:15:03.718Z	DEBUG	controller.machine.lifecycle	registered machine	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-72mzr", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2a/i-***", "node": "ip-10-53-240-7.us-west-2.compute.internal"}
2023-09-21T13:15:36.822Z	DEBUG	controller.machine.lifecycle	initialized machine	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-72mzr", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2a/i-***", "node": "ip-10-53-240-7.us-west-2.compute.internal"}
2023-09-21T13:15:59.689Z	DEBUG	controller	deleted launch template	{"commit": "637a642", "id": "lt-0087ed24d60909b56", "name": "karpenter.k8s.aws/18266737407409087375"}
2023-09-21T13:16:10.237Z	INFO	controller.deprovisioning	deprovisioning via consolidation replace, terminating 1 machines ip-10-53-240-7.us-west-2.compute.internal/c6a.4xlarge/on-demand and replacing with on-demand machine from types r6a.xlarge, r6i.xlarge, r6a.2xlarge, m6id.xlarge, c7i.2xlarge and 31 other(s)	{"commit": "637a642"}
2023-09-21T13:16:10.299Z	INFO	controller.deprovisioning	created machine	{"commit": "637a642", "provisioner": "fake-sample-service-usw2-dev-default", "machine": "fake-sample-service-usw2-dev-default-6z5qm", "requests": {"cpu":"2490m","memory":"5233272064","pods":"10"}, "instance-types": "c6a.2xlarge, c6a.xlarge, c6i.2xlarge, c6i.xlarge, c6id.2xlarge and 31 other(s)"}
2023-09-21T13:16:10.449Z	DEBUG	controller.machine.lifecycle	discovered subnets	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-6z5qm", "provisioner": "fake-sample-service-usw2-dev-default", "subnets": ["subnet-0282303dcb0702609 (us-west-2c)", "subnet-0650553d00f415a5c (us-west-2b)", "subnet-0270dd49606120b3b (us-west-2a)"]}
2023-09-21T13:16:10.810Z	DEBUG	controller.machine.lifecycle	created launch template	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-6z5qm", "provisioner": "fake-sample-service-usw2-dev-default", "launch-template-name": "karpenter.k8s.aws/18266737407409087375", "id": "lt-03ea7ab4080af9339"}
2023-09-21T13:16:12.669Z	INFO	controller.machine.lifecycle	launched machine	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-6z5qm", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2b/i-***", "instance-type": "c6a.xlarge", "zone": "us-west-2b", "capacity-type": "on-demand", "allocatable": {"cpu":"3920m","ephemeral-storage":"122621316300","memory":"6584Mi","pods":"58"}}
2023-09-21T13:17:18.321Z	DEBUG	controller.machine.lifecycle	registered machine	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-6z5qm", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2b/i-***", "node": "ip-10-53-243-144.us-west-2.compute.internal"}
2023-09-21T13:17:19.199Z	DEBUG	controller.node_state	discovered subnets	{"commit": "637a642", "node": "ip-10-53-243-144.us-west-2.compute.internal", "subnets": ["subnet-0282303dcb0702609 (us-west-2c)", "subnet-0650553d00f415a5c (us-west-2b)", "subnet-0270dd49606120b3b (us-west-2a)"]}
2023-09-21T13:18:06.685Z	DEBUG	controller.machine.lifecycle	initialized machine	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-6z5qm", "provisioner": "fake-sample-service-usw2-dev-default", "provider-id": "aws:///us-west-2b/i-***", "node": "ip-10-53-243-144.us-west-2.compute.internal"}
2023-09-21T13:18:14.635Z	INFO	controller.termination	cordoned node	{"commit": "637a642", "node": "ip-10-53-240-7.us-west-2.compute.internal"}
2023-09-21T13:18:17.367Z	INFO	controller.termination	deleted node	{"commit": "637a642", "node": "ip-10-53-240-7.us-west-2.compute.internal"}
2023-09-21T13:18:17.632Z	INFO	controller.machine.termination	deleted machine	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-72mzr", "provisioner": "fake-sample-service-usw2-dev-default", "node": "ip-10-53-240-7.us-west-2.compute.internal", "provider-id": "aws:///us-west-2a/i-***"}
2023-09-21T13:19:04.152Z	INFO	controller.termination	cordoned node	{"commit": "637a642", "node": "ip-10-53-243-144.us-west-2.compute.internal"}
2023-09-21T13:19:05.709Z	INFO	controller.termination	deleted node	{"commit": "637a642", "node": "ip-10-53-243-144.us-west-2.compute.internal"}
2023-09-21T13:19:06.010Z	INFO	controller.machine.termination	deleted machine	{"commit": "637a642", "machine": "fake-sample-service-usw2-dev-default-6z5qm", "provisioner": "fake-sample-service-usw2-dev-default", "node": "ip-10-53-243-144.us-west-2.compute.internal", "provider-id": "aws:///us-west-2b/i-***"}
2023-09-21T13:21:17.135Z	DEBUG	controller.awsnodetemplate	discovered subnets	{"commit": "637a642", "awsnodetemplate": "custom-family", "subnets": ["subnet-0282303dcb0702609 (us-west-2c)", "subnet-0650553d00f415a5c (us-west-2b)", "subnet-0270dd49606120b3b (us-west-2a)"]}
2023-09-21T13:25:59.683Z	DEBUG	controller	deleted launch template	{"commit": "637a642", "id": "lt-03ea7ab4080af9339", "name": "karpenter.k8s.aws/18266737407409087375"}
```
Will also attach a video in the slack thread: https://kubernetes.slack.com/archives/C02SFFZSA2K/p1695232856184679?thread_ts=1695184803.826269&cid=C02SFFZSA2K

**Comment by njtran** [comment]
Copying resource specs from the slack thread here 

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: fake-sample-service-usw2-dev
  labels:
    name: fake-sample-service-usw2-dev
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: fake-sample-service-usw2-dev-default
spec:
  consolidation:
    enabled: true
  taints:
    - key: ig/fakesampleserviceusw2devdefault
      effect: NoSchedule
    - key: ig/fakesampleserviceusw2devdefault
      effect: NoExecute
  labels:
    node.kubernetes.io/instancegroup: fake-sample-service-usw2-dev-default
    node.kubernetes.io/role: fake-sample-service-usw2-dev-default
  providerRef:
    name: custom-family
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ['m','c','r']
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ['5']
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-sample-service
  name: fake-sample-service-deployment
  namespace: fake-sample-service-usw2-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-sample-service
  template:
    metadata:
      labels:
        app: fake-sample-service
    spec:
      tolerations:
        - key: ig/fakesampleserviceusw2devdefault
      nodeSelector:
        node.kubernetes.io/instancegroup: fake-sample-service-usw2-dev-default
      containers:
        - image: <private-docker-repo>/ticker:0.1
          name: app
          resources:  {"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}}
```

**Comment by engedaam** [comment]
@rkilingr I have not been able to reproduce this issue. I see from the video there are several Daemonsets that are placed on the node. Would you be able share those pods, as well?
